import { test, expect } from '@playwright/test'

test('default demo is wallet-free, local-only and mobile-safe', async ({ page }) => {
  const remote: string[] = []; const errors: string[] = []
  page.on('request', r => { if (new URL(r.url()).origin !== new URL(process.env.DEMO_URL || 'http://127.0.0.1:4173').origin) remote.push(r.url()) })
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('./')
  await expect(page.getByRole('heading', { name: /规则与资金流/ })).toBeVisible()
  await expect(page.getByTestId('usdc-balance')).toHaveText('25,000.00')
  await expect(page.getByText('模拟模式 · 无需钱包', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(remote).toEqual([]); expect(errors).toEqual([])
})
test('subscription and T+2 redemption change balances exactly once', async ({ page }) => {
  await page.goto('./')
  await page.getByLabel('申购金额', { exact: true }).fill('102')
  await page.getByRole('button', { name: '申购 tBILL', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('100.00 tBILL')
  await page.getByLabel('赎回数量').fill('100')
  await page.getByRole('button', { name: '申请赎回', exact: true }).click()
  await expect(page.getByRole('button', { name: '领取', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: /推进 1 天/ }).click()
  await page.getByRole('button', { name: /推进 1 天/ }).click()
  await page.getByRole('button', { name: '领取', exact: true }).click()
  await expect(page.getByTestId('usdc-balance')).toHaveText('25,000.00')
  await expect(page.getByRole('button', { name: '已领取', exact: true })).toBeDisabled()
})
test('risk switches show refusals and vault deposits/withdrawals update shares', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'KYC：已验证', exact: true }).click()
  await page.getByLabel('申购金额', { exact: true }).fill('100')
  await page.getByRole('button', { name: '申购 tBILL', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('KYC 拒绝')
  await page.getByRole('button', { name: 'KYC：未验证', exact: true }).click()
  await page.getByRole('button', { name: 'NAV：有效', exact: true }).click()
  await page.getByRole('button', { name: '申购 tBILL', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('NAV 已过期')
  await page.getByLabel('金库存入金额', { exact: true }).fill('10000')
  await page.getByRole('button', { name: '存入金库', exact: true }).click()
  await expect(page.getByTestId('vault-shares')).toHaveText('10,000.00 lienUSDC')
  await page.getByRole('button', { name: '耗尽市场流动性', exact: true }).click()
  await expect(page.getByTestId('vault-available')).toHaveText('2,000.00 USDC')
  await page.getByLabel('金库提取金额', { exact: true }).fill('3000')
  await page.getByRole('button', { name: '提取 USDC', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('流动性不足')
  await page.getByLabel('金库提取金额', { exact: true }).fill('2000')
  await page.getByRole('button', { name: '提取 USDC', exact: true }).click()
  await expect(page.getByTestId('vault-shares')).toHaveText('8,000.00 lienUSDC')
  await page.getByRole('button', { name: '重置演示', exact: true }).click()
  await expect(page.getByTestId('vault-shares')).toHaveText('0.00 lienUSDC')
})

test('testnet RPC outage fails closed and returning to demo resets balances', async ({ page }) => {
  await page.route('https://sepolia.base.org/**', route => route.abort('connectionfailed'))
  await page.goto('./')
  await page.getByLabel('金库存入金额', { exact: true }).fill('100')
  await page.getByRole('button', { name: '存入金库', exact: true }).click()
  await page.getByRole('button', { name: 'Base Sepolia · 测试网', exact: true }).click()
  await expect(page.getByText('NAV 状态未知 / unavailable')).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('button', { name: '授权并存入', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '模拟体验 · 无需钱包', exact: true }).click()
  await expect(page.getByTestId('vault-shares')).toHaveText('0.00 lienUSDC')
  await expect(page.getByTestId('usdc-balance')).toHaveText('25,000.00')
})
